// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0EVWu4eTnX8qQsyNPlfX8i8d70jmv6Hk',
    appId: '1:754824758177:android:edf0c33b5072c3b1c701e0',
    messagingSenderId: '754824758177',
    projectId: 'flutterapp-bd8e0',
    databaseURL: 'https://flutterapp-bd8e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-bd8e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYl9ypMPfcgrhJlF14nCD23ct_B21Zq1Q',
    appId: '1:754824758177:ios:d19b2c2e4f258cc0c701e0',
    messagingSenderId: '754824758177',
    projectId: 'flutterapp-bd8e0',
    databaseURL: 'https://flutterapp-bd8e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-bd8e0.firebasestorage.app',
    iosBundleId: 'com.example.irajeApp',
  );
}
